<?php
/**
 * OrderStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * OrderStatus Class Doc Comment
 *
 * @category Class
 * @description Статус заявки
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderStatus
{
    /**
     * Possible values of this enum
     */
    const _NEW = 'New';
const PARTIALLY_FILL = 'PartiallyFill';
const FILL = 'Fill';
const CANCELLED = 'Cancelled';
const REPLACED = 'Replaced';
const PENDING_CANCEL = 'PendingCancel';
const REJECTED = 'Rejected';
const PENDING_REPLACE = 'PendingReplace';
const PENDING_NEW = 'PendingNew';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
self::PARTIALLY_FILL,
self::FILL,
self::CANCELLED,
self::REPLACED,
self::PENDING_CANCEL,
self::REJECTED,
self::PENDING_REPLACE,
self::PENDING_NEW,        ];
    }
}
