<?php
/**
 * CandleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CandleTest Class Doc Comment
 *
 * @category    Class
 * @description Candle
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CandleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Candle"
     */
    public function testCandle()
    {
    }

    /**
     * Test attribute "figi"
     */
    public function testPropertyFigi()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "o"
     */
    public function testPropertyO()
    {
    }

    /**
     * Test attribute "c"
     */
    public function testPropertyC()
    {
    }

    /**
     * Test attribute "h"
     */
    public function testPropertyH()
    {
    }

    /**
     * Test attribute "l"
     */
    public function testPropertyL()
    {
    }

    /**
     * Test attribute "v"
     */
    public function testPropertyV()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }
}
