<?php
/**
 * OrderbookTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderbookTest Class Doc Comment
 *
 * @category    Class
 * @description Orderbook
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderbookTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Orderbook"
     */
    public function testOrderbook()
    {
    }

    /**
     * Test attribute "figi"
     */
    public function testPropertyFigi()
    {
    }

    /**
     * Test attribute "depth"
     */
    public function testPropertyDepth()
    {
    }

    /**
     * Test attribute "bids"
     */
    public function testPropertyBids()
    {
    }

    /**
     * Test attribute "asks"
     */
    public function testPropertyAsks()
    {
    }

    /**
     * Test attribute "trade_status"
     */
    public function testPropertyTradeStatus()
    {
    }

    /**
     * Test attribute "min_price_increment"
     */
    public function testPropertyMinPriceIncrement()
    {
    }

    /**
     * Test attribute "face_value"
     */
    public function testPropertyFaceValue()
    {
    }

    /**
     * Test attribute "last_price"
     */
    public function testPropertyLastPrice()
    {
    }

    /**
     * Test attribute "close_price"
     */
    public function testPropertyClosePrice()
    {
    }

    /**
     * Test attribute "limit_up"
     */
    public function testPropertyLimitUp()
    {
    }

    /**
     * Test attribute "limit_down"
     */
    public function testPropertyLimitDown()
    {
    }
}
