<?php
/**
 * MarketApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MarketApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MarketApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for marketBondsGet
     *
     * Получение списка облигаций.
     *
     */
    public function testMarketBondsGet()
    {
    }

    /**
     * Test case for marketCandlesGet
     *
     * Получение исторических свечей по FIGI.
     *
     */
    public function testMarketCandlesGet()
    {
    }

    /**
     * Test case for marketCurrenciesGet
     *
     * Получение списка валютных пар.
     *
     */
    public function testMarketCurrenciesGet()
    {
    }

    /**
     * Test case for marketEtfsGet
     *
     * Получение списка ETF.
     *
     */
    public function testMarketEtfsGet()
    {
    }

    /**
     * Test case for marketOrderbookGet
     *
     * Получение стакана по FIGI.
     *
     */
    public function testMarketOrderbookGet()
    {
    }

    /**
     * Test case for marketSearchByFigiGet
     *
     * Получение инструмента по FIGI.
     *
     */
    public function testMarketSearchByFigiGet()
    {
    }

    /**
     * Test case for marketSearchByTickerGet
     *
     * Получение инструмента по тикеру.
     *
     */
    public function testMarketSearchByTickerGet()
    {
    }

    /**
     * Test case for marketStocksGet
     *
     * Получение списка акций.
     *
     */
    public function testMarketStocksGet()
    {
    }
}
